/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.14
 * Generated at: 2022-03-24 12:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import mipk.beanDB;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mipk.beanDB");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html><head>\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400\">  <!-- Google web font \"Open Sans\" -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/fontawesome-all.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/magnific-popup.css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"slick/slick.css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"slick/slick-theme.css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/tooplate-style.css\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <style>\r\n");
      out.write("    body {\r\n");
      out.write("        padding-top: 70px;\r\n");
      out.write("        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("<script>\r\n");
      out.write("		var renderPage = true;\r\n");
      out.write("\r\n");
      out.write("	if(navigator.userAgent.indexOf('MSIE')!==-1\r\n");
      out.write("		|| navigator.appVersion.indexOf('Trident/') > 0){\r\n");
      out.write("   		/* Microsoft Internet Explorer detected in. */\r\n");
      out.write("   		alert(\"Please view this in a modern browser such as Chrome or Microsoft Edge.\");\r\n");
      out.write("   		renderPage = false;\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</head><body>\r\n");
      out.write("<br/>\r\n");
      out.write("<!---\r\n");
      out.write("<form action=\"BBDD\" method=\"get\">\r\n");
      out.write("       <table class=\"Primary\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                   <div class=\"row-g3\">\r\n");
      out.write("                    <label class=\"form-label\">Query</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"laQuery\" placeholder=\"Ej: Select * From Alumnos;\" >\r\n");
      out.write("                  </div> \r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                     <div class=\"row-g3\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary mb-3\">Ejecutar</button>\r\n");
      out.write("  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("-->\r\n");
      out.write("<!-- Loader -->\r\n");
      out.write("	<div id=\"loader-wrapper\">\r\n");
      out.write("		<div id=\"loader\"></div>\r\n");
      out.write("		<div class=\"loader-section section-left\"></div>\r\n");
      out.write("		<div class=\"loader-section section-right\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Page Content -->\r\n");
      out.write("	<div class=\"container-fluid tm-main\">\r\n");
      out.write("		<div class=\"row tm-main-row\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Sidebar -->\r\n");
      out.write("			<div id=\"tmSideBar\" class=\"col-xl-3 col-lg-4 col-md-12 col-sm-12 sidebar\">\r\n");
      out.write("\r\n");
      out.write("				<button id=\"tmMainNavToggle\" class=\"menu-icon\">&#9776;</button>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"inner\">\r\n");
      out.write("					<nav id=\"tmMainNav\" class=\"tm-main-nav\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"#intro\" id=\"tmNavLink1\" class=\"scrolly active\" data-bg-img=\"constructive_bg_01.jpg\" data-page=\"#tm-section-1\">\r\n");
      out.write("									<i class=\"fas fa-home tm-nav-fa-icon\"></i>\r\n");
      out.write("									<span>Introduction</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"#products\" id=\"tmNavLink2\" class=\"scrolly\" data-bg-img=\"constructive_bg_02.jpg\" data-page=\"#tm-section-2\" data-page-type=\"carousel\">\r\n");
      out.write("									<i class=\"fas fa-map tm-nav-fa-icon\"></i>\r\n");
      out.write("									<span>Listado De Asignaturas</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>							\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"#company\" class=\"scrolly\" data-bg-img=\"constructive_bg_03.jpg\" data-page=\"#tm-section-3\">\r\n");
      out.write("									<i class=\"fas fa-users tm-nav-fa-icon\"></i>\r\n");
      out.write("									<span>Listado de Alumnos</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li>\r\n");
      out.write("								<a href=\"#contact\" class=\"scrolly\" data-bg-img=\"constructive_bg_04.jpg\" data-page=\"#tm-section-4\">\r\n");
      out.write("									<i class=\"fas fa-comments tm-nav-fa-icon\"></i>\r\n");
      out.write("									<span>Contact Us</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-xl-9 col-lg-8 col-md-12 col-sm-12 tm-content\">\r\n");
      out.write("\r\n");
      out.write("					<!-- section 1 -->\r\n");
      out.write("					<section id=\"tm-section-1\" class=\"tm-section\">\r\n");
      out.write("						<div class=\"ml-auto\">\r\n");
      out.write("							<header class=\"mb-4\"><h1 class=\"tm-text-shadow\">Constructive Design</h1></header>\r\n");
      out.write("							<p class=\"mb-5 tm-font-big\">Aenean fermentum vestibulum ipsum, ut pretium erat sodales sodales. Pellentesque quis orci vitae dui commodo sodales et ut quam. Etiam vitae egestas purus, ut malesuada enim.</p>\r\n");
      out.write("							<a href=\"#\" class=\"btn tm-btn tm-font-big\" data-nav-link=\"#tmNavLink2\">Continue...</a> \r\n");
      out.write("							<!-- data-nav-link holds the ID of nav item, which means this link should behave the same as that nav item  -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<!-- section 2 -->\r\n");
      out.write("					<section id=\"tm-section-2\" class=\"tm-section tm-section-carousel\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<header class=\"mb-4\"><h2 class=\"tm-text-shadow\">Listado De Asignaturas</h2></header>		            \r\n");
      out.write("							<div class=\"tm-img-container\">\r\n");
      out.write("							");
 
							String query="Select * FROM Asignaturas;";
							//String query="select * from Asignaturas;";
beanDB basededatos = new beanDB();
String [][] tablares = basededatos.resConsultaSelectA3(query);

      out.write(" \r\n");
      out.write("<table class=\"table table-dark table-striped\"\">\r\n");
 for (int i=0; i<tablares.length;i++) {
//	
      out.write("<tr> ");

	for (int j=0; j<tablares[i].length;j++) {
	
      out.write(" <td> ");
      out.print(tablares[i][j] );
      out.write(" </td> ");

	}
	
      out.write(" </tr> ");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("							</div>		            		          \r\n");
      out.write("						</div>       		          	\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<!-- section 3 -->\r\n");
      out.write("					<section id=\"tm-section-3\" class=\"tm-section tm-section-carousel\">						\r\n");
      out.write("						<div class=\"row mb-4\">\r\n");
      out.write("							<header class=\"col-xl-12\"><h2 class=\"tm-text-shadow\">Listado De Alumnos</h2></header>		\r\n");
      out.write("						<div class=\"tm-img-container\">\r\n");
      out.write("													");
 
String queryAlumnos="select * from Alumnos;";
String [][] tablaAlumnos = basededatos.resConsultaSelectA3(queryAlumnos);

      out.write(" \r\n");
      out.write("<table class=\"table table-dark table-striped\"\">\r\n");
 for (int i=0; i<tablaAlumnos.length;i++) {
//	
      out.write("<tr> ");

	for (int j=0; j<tablaAlumnos[i].length;j++) {
	
      out.write(" <td> ");
      out.print(tablaAlumnos[i][j] );
      out.write(" </td> ");

	}
	
      out.write(" </tr> ");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>				\r\n");
      out.write("</div>		               \r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<!-- section 4 -->\r\n");
      out.write("					<section id=\"tm-section-4\" class=\"tm-section\">\r\n");
      out.write("						<div class=\"tm-bg-transparent-black tm-contact-box-pad\">\r\n");
      out.write("							<div class=\"row mb-4\">\r\n");
      out.write("								<div class=\"col-sm-12\">\r\n");
      out.write("									<header><h2 class=\"tm-text-shadow\">Contact Us</h2></header>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"row tm-page-4-content\">\r\n");
      out.write("								<div class=\"col-md-6 col-sm-12 tm-contact-col\">\r\n");
      out.write("									<div class=\"contact_message\">\r\n");
      out.write("										<form action=\"#contact\" method=\"post\" class=\"contact-form\">\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"text\" id=\"contact_name\" name=\"contact_name\" class=\"form-control\" placeholder=\"Name\" required>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<input type=\"email\" id=\"contact_email\" name=\"contact_email\" class=\"form-control\" placeholder=\"Email\" required>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"form-group\">\r\n");
      out.write("												<textarea id=\"contact_message\" name=\"contact_message\" class=\"form-control\" rows=\"9\" placeholder=\"Message\" required></textarea>\r\n");
      out.write("											</div>\r\n");
      out.write("											<button type=\"submit\" class=\"btn tm-btn-submit tm-btn ml-auto\">Submit</button>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6 col-sm-12 tm-contact-col\">\r\n");
      out.write("									<div class=\"tm-address-box\">\r\n");
      out.write("										<p>Aliquam interdum, nisl sedd faucibus tempor, massa velit laoreet ipsum, et faucibus sapien magna at enim. Suspendisse a dictum tortor.</p>\r\n");
      out.write("										<p>Curabitur venenatis leo in augue convallis, vulputate sollicitudin ex maximus.</p>\r\n");
      out.write("										<address>\r\n");
      out.write("											120-240 Aliquam nec neque augue<br>\r\n");
      out.write("											Suspendisse tincidunt nunc,<br>\r\n");
      out.write("											vitae sagis justo 11000\r\n");
      out.write("										</address>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>					\r\n");
      out.write("				</div>	<!-- .tm-content -->							\r\n");
      out.write("				\r\n");
      out.write("			</div>	<!-- row -->			\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"preload-01\"></div>\r\n");
      out.write("		<div id=\"preload-02\"></div>\r\n");
      out.write("		<div id=\"preload-03\"></div>\r\n");
      out.write("		<div id=\"preload-04\"></div>\r\n");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\" src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"js/jquery.backstretch.min.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"slick/slick.min.js\"></script> <!-- Slick Carousel -->\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("\r\n");
      out.write("		var sidebarVisible = false;\r\n");
      out.write("		var currentPageID = \"#tm-section-1\";\r\n");
      out.write("\r\n");
      out.write("		// Setup Carousel\r\n");
      out.write("		function setupCarousel() {\r\n");
      out.write("\r\n");
      out.write("			// If current page isn't Carousel page, don't do anything.\r\n");
      out.write("			if($('#tm-section-2').css('display') == \"none\") {\r\n");
      out.write("			}\r\n");
      out.write("			else {	// If current page is Carousel page, set up the Carousel.\r\n");
      out.write("\r\n");
      out.write("				var slider = $('.tm-img-slider');\r\n");
      out.write("				var windowWidth = $(window).width();\r\n");
      out.write("\r\n");
      out.write("				if (slider.hasClass('slick-initialized')) {\r\n");
      out.write("					slider.slick('destroy');\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				if(windowWidth < 640) {\r\n");
      out.write("					slider.slick({\r\n");
      out.write("	              		dots: true,\r\n");
      out.write("	              		infinite: false,\r\n");
      out.write("	              		slidesToShow: 1,\r\n");
      out.write("	              		slidesToScroll: 1\r\n");
      out.write("	              	});\r\n");
      out.write("				}\r\n");
      out.write("				else if(windowWidth < 992) {\r\n");
      out.write("					slider.slick({\r\n");
      out.write("	              		dots: true,\r\n");
      out.write("	              		infinite: false,\r\n");
      out.write("	              		slidesToShow: 2,\r\n");
      out.write("	              		slidesToScroll: 1\r\n");
      out.write("	              	});\r\n");
      out.write("				}\r\n");
      out.write("				else {\r\n");
      out.write("					// Slick carousel\r\n");
      out.write("	              	slider.slick({\r\n");
      out.write("	              		dots: true,\r\n");
      out.write("	              		infinite: false,\r\n");
      out.write("	              		slidesToShow: 3,\r\n");
      out.write("	              		slidesToScroll: 2\r\n");
      out.write("	              	});\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				// Init Magnific Popup\r\n");
      out.write("				$('.tm-img-slider').magnificPopup({\r\n");
      out.write("				  delegate: 'a', // child items selector, by clicking on it popup will open\r\n");
      out.write("				  type: 'image',\r\n");
      out.write("				  gallery: {enabled:true}\r\n");
      out.write("				  // other options\r\n");
      out.write("				});\r\n");
      out.write("      		}\r\n");
      out.write("  		}\r\n");
      out.write("\r\n");
      out.write("  		// Setup Nav\r\n");
      out.write("  		function setupNav() {\r\n");
      out.write("  			// Add Event Listener to each Nav item\r\n");
      out.write("	     	$(\".tm-main-nav a\").click(function(e){\r\n");
      out.write("	     		e.preventDefault();\r\n");
      out.write("		    	\r\n");
      out.write("		    	var currentNavItem = $(this);\r\n");
      out.write("		    	changePage(currentNavItem);\r\n");
      out.write("		    	\r\n");
      out.write("		    	setupCarousel();\r\n");
      out.write("		    	setupFooter();\r\n");
      out.write("\r\n");
      out.write("		    	// Hide the nav on mobile\r\n");
      out.write("		    	$(\"#tmSideBar\").removeClass(\"show\");\r\n");
      out.write("		    });	    \r\n");
      out.write("  		}\r\n");
      out.write("\r\n");
      out.write("  		function changePage(currentNavItem) {\r\n");
      out.write("  			// Update Nav items\r\n");
      out.write("  			$(\".tm-main-nav a\").removeClass(\"active\");\r\n");
      out.write("     		currentNavItem.addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("	    	$(currentPageID).hide();\r\n");
      out.write("\r\n");
      out.write("	    	// Show current page\r\n");
      out.write("	    	currentPageID = currentNavItem.data(\"page\");\r\n");
      out.write("	    	$(currentPageID).fadeIn(1000);\r\n");
      out.write("\r\n");
      out.write("	    	// Change background image\r\n");
      out.write("	    	var bgImg = currentNavItem.data(\"bgImg\");\r\n");
      out.write("	    	$.backstretch(\"img/\" + bgImg);		    	\r\n");
      out.write("  		}\r\n");
      out.write("\r\n");
      out.write("  		// Setup Nav Toggle Button\r\n");
      out.write("  		function setupNavToggle() {\r\n");
      out.write("\r\n");
      out.write("			$(\"#tmMainNavToggle\").on(\"click\", function(){\r\n");
      out.write("				$(\".sidebar\").toggleClass(\"show\");\r\n");
      out.write("			});\r\n");
      out.write("  		}\r\n");
      out.write("\r\n");
      out.write("  		// If there is enough room, stick the footer at the bottom of page content.\r\n");
      out.write("  		// If not, place it after the page content\r\n");
      out.write("  		function setupFooter() {\r\n");
      out.write("  			\r\n");
      out.write("  			var padding = 100;\r\n");
      out.write("  			var footerPadding = 40;\r\n");
      out.write("  			var mainContent = $(\"section\"+currentPageID);\r\n");
      out.write("  			var mainContentHeight = mainContent.outerHeight(true);\r\n");
      out.write("  			var footer = $(\".footer-link\");\r\n");
      out.write("  			var footerHeight = footer.outerHeight(true);\r\n");
      out.write("  			var totalPageHeight = mainContentHeight + footerHeight + footerPadding + padding;\r\n");
      out.write("  			var windowHeight = $(window).height();		\r\n");
      out.write("\r\n");
      out.write("  			if(totalPageHeight > windowHeight){\r\n");
      out.write("  				$(\".tm-content\").css(\"margin-bottom\", footerHeight + footerPadding + \"px\");\r\n");
      out.write("  				footer.css(\"bottom\", footerHeight + \"px\");  			\r\n");
      out.write("  			}\r\n");
      out.write("  			else {\r\n");
      out.write("  				$(\".tm-content\").css(\"margin-bottom\", \"0\");\r\n");
      out.write("  				footer.css(\"bottom\", \"20px\");  				\r\n");
      out.write("  			}  			\r\n");
      out.write("  		}\r\n");
      out.write("\r\n");
      out.write("  		// Everything is loaded including images.\r\n");
      out.write("      	$(window).on(\"load\", function(){\r\n");
      out.write("\r\n");
      out.write("      		// Render the page on modern browser only.\r\n");
      out.write("      		if(renderPage) {\r\n");
      out.write("				// Remove loader\r\n");
      out.write("		      	$('body').addClass('loaded');\r\n");
      out.write("\r\n");
      out.write("		      	// Page transition\r\n");
      out.write("		      	var allPages = $(\".tm-section\");\r\n");
      out.write("\r\n");
      out.write("		      	// Handle click of \"Continue\", which changes to next page\r\n");
      out.write("		      	// The link contains data-nav-link attribute, which holds the nav item ID\r\n");
      out.write("		      	// Nav item ID is then used to access and trigger click on the corresponding nav item\r\n");
      out.write("		      	var linkToAnotherPage = $(\"a.tm-btn[data-nav-link]\");\r\n");
      out.write("			    \r\n");
      out.write("			    if(linkToAnotherPage != null) {\r\n");
      out.write("			    	\r\n");
      out.write("			    	linkToAnotherPage.on(\"click\", function(){\r\n");
      out.write("			    		var navItemToHighlight = linkToAnotherPage.data(\"navLink\");\r\n");
      out.write("			    		$(\"a\" + navItemToHighlight).click();\r\n");
      out.write("			    	});\r\n");
      out.write("			    }\r\n");
      out.write("		      	\r\n");
      out.write("		      	// Hide all pages\r\n");
      out.write("		      	allPages.hide();\r\n");
      out.write("\r\n");
      out.write("		      	$(\"#tm-section-1\").fadeIn();\r\n");
      out.write("\r\n");
      out.write("		     	// Set up background first page\r\n");
      out.write("		     	var bgImg = $(\"#tmNavLink1\").data(\"bgImg\");\r\n");
      out.write("		     	\r\n");
      out.write("		     	$.backstretch(\"img/\" + bgImg, {fade: 500});\r\n");
      out.write("\r\n");
      out.write("		     	// Setup Carousel, Nav, and Nav Toggle\r\n");
      out.write("			    setupCarousel();\r\n");
      out.write("			    setupNav();\r\n");
      out.write("			    setupNavToggle();\r\n");
      out.write("			    setupFooter();\r\n");
      out.write("\r\n");
      out.write("			    // Resize Carousel upon window resize\r\n");
      out.write("			    $(window).resize(function() {\r\n");
      out.write("			    	setupCarousel();\r\n");
      out.write("			    	setupFooter();\r\n");
      out.write("			    });\r\n");
      out.write("      		}	      	\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		</script>\r\n");
 
//String query="select nombre, apellidos, COUNT(id_Alumno) from Alumnos  group by id_Alumno order by count(id_Alumno) DESC;";
//beanDB basededatos = new beanDB();
//String [][] tablares = basededatos.resConsultaSelectA3(query);

      out.write(" \r\n");
      out.write("<table>\r\n");
// for (int i=0; i<tablares.length;i++) {
//	
      out.write("<tr> ");

	//for (int j=0; j<tablares[i].length;j++) {
	//
      out.write(" <td> ");
//=tablares[i][j] 
      out.write(" </td> ");

	//}
	//
      out.write(" </tr> ");

//}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
